import json
import requests


# JSON file generated by YOLO activity detection
JSON_FILE = "activity_results.json"

# FastAPI activity endpoint
API_URL = "http://127.0.0.1:8000/api/v1/activity"


# ------------------------------------------------------------
# Read JSON
# ------------------------------------------------------------

with open(
    JSON_FILE,
    "r",
    encoding="utf-8"
) as file:

    data = json.load(file)


# ------------------------------------------------------------
# Send JSON to FastAPI
# ------------------------------------------------------------

response = requests.post(
    API_URL,
    json=data
)


# ------------------------------------------------------------
# Display response
# ------------------------------------------------------------

print("Status code:", response.status_code)

print("Response:")

try:
    print(response.json())

except Exception:
    print(response.text)